WITH SUB AS (
SELECT TO_CHAR(SALE.SALES_DATE, 'YYYY') YEAR
     , TO_NUMBER(TO_CHAR(SALE.SALES_DATE, 'MM')) MONTH
     , USR.USER_ID 
     , USR.GENDER
FROM USER_INFO USR
INNER JOIN ONLINE_SALE SALE
    ON SALE.USER_ID = USR.USER_ID
WHERE USR.GENDER IS NOT NULL 
)
SELECT YEAR
     , MONTH
     , GENDER
     , COUNT(DISTINCT USER_ID) USERS
FROM SUB
GROUP BY YEAR
       , MONTH
       , GENDER
ORDER BY YEAR
       , MONTH
       , GENDER;