-- 코드를 입력하세요
WITH TEMP AS (
    SELECT NAME, DATETIME, (ROW_NUMBER() OVER (ORDER BY DATETIME)) AS N
    FROM ANIMAL_INS
    WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
)
SELECT NAME, DATETIME
FROM TEMP
WHERE N < 4